import type { TestDefinition } from "./types";

/**
 * S1 v1 test catalog for Report 1’s seven domains (guideline §8.2 / §8.7).
 *
 * Rules:
 * - TEST_ID is the database key. Display copy is not.
 * - Feature-based, not `if (model === "S21")`.
 * - Phone vs tablet: no SIM is not a defect (telephony feature absent → NOT_SUPPORTED).
 * - IMEI, hardware serial, battery SOH, and Knox attestation cannot PASS from S1.
 */

export const ANDROID_FEATURES = {
  CAMERA: "android.hardware.camera",
  CAMERA_FRONT: "android.hardware.camera.front",
  CAMERA_ANY: "android.hardware.camera.any",
  TOUCHSCREEN: "android.hardware.touchscreen",
  MICROPHONE: "android.hardware.microphone",
  WIFI: "android.hardware.wifi",
  BLUETOOTH: "android.hardware.bluetooth",
  TELEPHONY: "android.hardware.telephony",
  AUDIO_OUTPUT: "android.hardware.audio.output",
  SENSOR_ACCELEROMETER: "android.hardware.sensor.accelerometer",
  SENSOR_GYROSCOPE: "android.hardware.sensor.gyroscope",
  SENSOR_PROXIMITY: "android.hardware.sensor.proximity",
  SENSOR_LIGHT: "android.hardware.sensor.light",
  SENSOR_COMPASS: "android.hardware.sensor.compass",
} as const;

export const ANDROID_PERMISSIONS = {
  CAMERA: "android.permission.CAMERA",
  RECORD_AUDIO: "android.permission.RECORD_AUDIO",
  BLUETOOTH_CONNECT: "android.permission.BLUETOOTH_CONNECT",
  NEARBY_WIFI_DEVICES: "android.permission.NEARBY_WIFI_DEVICES",
  ACCESS_FINE_LOCATION: "android.permission.ACCESS_FINE_LOCATION",
  VIBRATE: "android.permission.VIBRATE",
} as const;

export const S1_TEST_CATALOG: readonly TestDefinition[] = [
  {
    testId: "IDN.BUILD_IDENTITY",
    domain: "IDENTITY_CONFIGURATION",
    userName: "Build identity",
    objectiveName: "Device build and configuration identity",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "IDN.ANDROID_ID",
    domain: "IDENTITY_CONFIGURATION",
    userName: "App-scoped Android ID",
    objectiveName: "Settings.Secure.ANDROID_ID (resettable, not IMEI)",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "IDN.IMEI_SERIAL",
    domain: "IDENTITY_CONFIGURATION",
    userName: "IMEI / hardware serial",
    objectiveName: "Non-resettable device identifiers",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S3_ENTERPRISE",
    s1ForbiddenPass: true,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "IDN.SCREEN_FORM",
    domain: "IDENTITY_CONFIGURATION",
    userName: "Screen form",
    objectiveName: "smallestScreenWidthDp form-factor snapshot",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "IDN.FEATURE_INVENTORY",
    domain: "IDENTITY_CONFIGURATION",
    userName: "Feature inventory",
    objectiveName: "PackageManager system feature declaration snapshot",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "PHY.HOUSING_OBSERVATION",
    domain: "PHYSICAL_CONDITION",
    userName: "Housing condition",
    objectiveName: "Technician housing condition observation",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "TECHNICIAN_OBSERVATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
    observationOnly: true,
  },
  {
    testId: "PHY.DISPLAY_OBSERVATION",
    domain: "PHYSICAL_CONDITION",
    userName: "Display condition",
    objectiveName: "Technician display condition observation",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "TECHNICIAN_OBSERVATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
    observationOnly: true,
  },
  {
    testId: "PHY.PORT_OBSERVATION",
    domain: "PHYSICAL_CONDITION",
    userName: "Port condition",
    objectiveName: "Technician port condition observation",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "TECHNICIAN_OBSERVATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
    observationOnly: true,
  },
  {
    testId: "HW.CAMERA_BACK",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Rear camera present",
    objectiveName: "Rear camera hardware declaration",
    requireFeatures: [ANDROID_FEATURES.CAMERA],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.CAMERA_FRONT",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Front camera present",
    objectiveName: "Front camera hardware declaration",
    requireFeatures: [ANDROID_FEATURES.CAMERA_FRONT],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.CAMERA_INVENTORY",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Camera inventory",
    objectiveName: "Camera2 cameraIdList inventory",
    requireFeatures: [ANDROID_FEATURES.CAMERA_ANY],
    requirePermissions: [ANDROID_PERMISSIONS.CAMERA],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.STORAGE_CAPACITY",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Storage capacity",
    objectiveName: "Internal storage capacity snapshot",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.MEMORY",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Memory",
    objectiveName: "ActivityManager memory snapshot",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.SENSOR_INVENTORY",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Sensor inventory",
    objectiveName: "SensorManager getSensorList inventory",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.VIBRATOR_PRESENT",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Vibrator present",
    objectiveName: "Vibrator.hasVibrator declaration",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "HW.TELEPHONY_PRESENT",
    domain: "HARDWARE_CONFIGURATION",
    userName: "Telephony present",
    objectiveName: "android.hardware.telephony feature declaration",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.CAMERA_BACK_CAPTURE",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Camera Check",
    objectiveName: "Camera Functional Verification (rear)",
    requireFeatures: [ANDROID_FEATURES.CAMERA],
    requirePermissions: [ANDROID_PERMISSIONS.CAMERA],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.CAMERA_FRONT_CAPTURE",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Front Camera Check",
    objectiveName: "Camera Functional Verification (front)",
    requireFeatures: [ANDROID_FEATURES.CAMERA_FRONT],
    requirePermissions: [ANDROID_PERMISSIONS.CAMERA],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.DISPLAY_RENDER",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Display Check",
    objectiveName: "Display Functional Verification",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.TOUCH_GRID",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Touch Check",
    objectiveName: "Touch Functional Verification",
    requireFeatures: [ANDROID_FEATURES.TOUCHSCREEN],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.SPEAKER",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Speaker Check",
    objectiveName: "Audio Output Functional Verification",
    requireFeatures: [ANDROID_FEATURES.AUDIO_OUTPUT],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.MICROPHONE",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Microphone Check",
    objectiveName: "Microphone Functional Verification",
    requireFeatures: [ANDROID_FEATURES.MICROPHONE],
    requirePermissions: [ANDROID_PERMISSIONS.RECORD_AUDIO],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.VIBRATION",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Vibration Check",
    objectiveName: "Vibrator Functional Verification",
    requireFeatures: [],
    requirePermissions: [ANDROID_PERMISSIONS.VIBRATE],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.ACCELEROMETER",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Accelerometer Check",
    objectiveName: "Accelerometer Functional Verification",
    requireFeatures: [ANDROID_FEATURES.SENSOR_ACCELEROMETER],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.GYROSCOPE",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Gyroscope Check",
    objectiveName: "Gyroscope Functional Verification",
    requireFeatures: [ANDROID_FEATURES.SENSOR_GYROSCOPE],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.PROXIMITY",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Proximity Check",
    objectiveName: "Proximity Sensor Functional Verification",
    requireFeatures: [ANDROID_FEATURES.SENSOR_PROXIMITY],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.AMBIENT_LIGHT",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Light Sensor Check",
    objectiveName: "Ambient Light Sensor Functional Verification",
    requireFeatures: [ANDROID_FEATURES.SENSOR_LIGHT],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "FN.MAGNETOMETER",
    domain: "FUNCTIONAL_VERIFICATION",
    userName: "Compass Check",
    objectiveName: "Magnetic Field Sensor Functional Verification",
    requireFeatures: [ANDROID_FEATURES.SENSOR_COMPASS],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "NET.WIFI",
    domain: "CONNECTIVITY",
    userName: "Wi-Fi Check",
    objectiveName: "Wi-Fi radio classification",
    requireFeatures: [ANDROID_FEATURES.WIFI],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "NET.BLUETOOTH",
    domain: "CONNECTIVITY",
    userName: "Bluetooth Check",
    objectiveName: "Bluetooth radio classification",
    requireFeatures: [ANDROID_FEATURES.BLUETOOTH],
    requirePermissions: [ANDROID_PERMISSIONS.BLUETOOTH_CONNECT],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "NET.ACTIVE_TRANSPORT",
    domain: "CONNECTIVITY",
    userName: "Network class",
    objectiveName: "Active transport classification (wifi/cellular/ethernet/none)",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "NET.CELLULAR",
    domain: "CONNECTIVITY",
    userName: "Cellular Check",
    objectiveName: "Cellular radio classification",
    requireFeatures: [ANDROID_FEATURES.TELEPHONY],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "PWR.BATTERY_STATUS",
    domain: "POWER_BATTERY_STORAGE",
    userName: "Battery status",
    objectiveName: "BatteryManager level, scale, plugged, EXTRA_HEALTH",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "PWR.BATTERY_SOH",
    domain: "POWER_BATTERY_STORAGE",
    userName: "Battery state of health",
    objectiveName: "Battery state of health (enterprise / flagged API)",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S3_ENTERPRISE",
    s1ForbiddenPass: true,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "PWR.STORAGE_FREE",
    domain: "POWER_BATTERY_STORAGE",
    userName: "Free storage",
    objectiveName: "Internal free-space snapshot",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "SEC.ACCESS_LEVEL",
    domain: "SECURITY_ACCESS_LIMITATIONS",
    userName: "Access level",
    objectiveName: "Session access level L0–L4 classification",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "SEC.LOCK_PRESENT",
    domain: "SECURITY_ACCESS_LIMITATIONS",
    userName: "Screen lock present",
    objectiveName: "KeyguardManager lock presence (detect only, no bypass)",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "SEC.USB_DATA",
    domain: "SECURITY_ACCESS_LIMITATIONS",
    userName: "USB data state",
    objectiveName: "USB connection classification independent of ADB",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "SEC.ADB_SETTING",
    domain: "SECURITY_ACCESS_LIMITATIONS",
    userName: "ADB setting",
    objectiveName: "ADB enabled setting (not authorized ADB)",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "SEC.PERMISSION_MATRIX",
    domain: "SECURITY_ACCESS_LIMITATIONS",
    userName: "Permission matrix",
    objectiveName: "Runtime permission grant snapshot",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S1_APPLICATION",
    s1ForbiddenPass: false,
    defaultUntested: "NOT_TESTED",
  },
  {
    testId: "SEC.KNOX_CLAIM",
    domain: "SECURITY_ACCESS_LIMITATIONS",
    userName: "Knox attestation",
    objectiveName: "Samsung Knox attestation / OEM authority",
    requireFeatures: [],
    requirePermissions: [],
    minSource: "S3_ENTERPRISE",
    s1ForbiddenPass: true,
    defaultUntested: "NOT_TESTED",
  },
];

export function getTestDefinition(testId: string): TestDefinition | undefined {
  return S1_TEST_CATALOG.find((test) => test.testId === testId);
}

export function catalogTestIds(): string[] {
  return S1_TEST_CATALOG.map((test) => test.testId);
}
