/*
 * WS-K3 - LICENCE REQUEST (spec 10, PURCHASE RECORD).
 * ==================================================
 *
 * Two additive changes, generated by `pnpm db:generate` from `schema.ts`.
 *
 * 1. `mobile_serials.requested_at`
 *    Spec 10 lists "Request date/time" among the purchase-record fields.
 *    `created_at` cannot carry it: that value is written by the registration
 *    bridge when the ROW is born, which may be months before the customer
 *    asks for anything. Stamping a request onto `created_at` would date it
 *    from an event that is not the request.
 *
 *    NULL means "never explicitly requested" - the truthful state of every
 *    row that exists today. No DEFAULT, no backfill: filling it in for
 *    existing rows would assert that somebody asked for something when
 *    nobody did, which is the fabricated fact this project keeps removing.
 *
 *    `IF NOT EXISTS` makes the column statement safe to re-run by hand
 *    against a database that already has it (ordered by the Chief Engineer,
 *    08-Oct-2026). Drizzle's own tracker prevents a second run regardless.
 *
 * 2. `audit_action_enum += 'LICENCE_REQUESTED'`
 *    Appended rather than inserted beside `SERIAL_CREATED`: PostgreSQL
 *    cannot reorder an enum's existing values without recreating the type.
 *
 *    THIS STATEMENT HAS NO `IF NOT EXISTS` - PostgreSQL does not accept that
 *    clause on `ADD VALUE`, and a DO-block wrapper would put an
 *    `ALTER TYPE ... ADD VALUE` inside a transaction, which is exactly the
 *    restriction that made this construct fragile before PG12. Re-running is
 *    prevented by drizzle's migration tracker (`__drizzle_migrations`), not
 *    by the DDL. Recorded here so nobody "fixes" it into something that
 *    fails on Neon.
 *
 * SNAPSHOT CHECK (ordered by the Chief Engineer, 08-Oct-2026)
 * ----------------------------------------------------------
 * `meta/0005_snapshot.json` does not exist although the journal carries
 * `idx: 5` (`0005_mobile_licences`). Generation still succeeded, because
 * drizzle-kit diffs `schema.ts` against the LAST snapshot on disk (0009)
 * rather than replaying every historical one - so the 0005 gap cannot poison
 * this diff. `meta/0010_snapshot.json` was written alongside this file and
 * contains both changes, and a second `pnpm db:generate` reports "No schema
 * changes", which is the proof that `schema.ts` and the snapshot agree.
 *
 * Rollback: DROP COLUMN "requested_at"; the enum value requires a type
 * recreation and is best left in place (labels are cheap and inert).
 *
 * NO Neon WRITE: `drizzle-kit generate` writes files only. Applying this
 * migration is a separate act and still requires named approval (Master
 * Plan section 9).
 */
--> statement-breakpoint
ALTER TYPE "public"."audit_action_enum" ADD VALUE 'LICENCE_REQUESTED';--> statement-breakpoint
ALTER TABLE "mobile_serials" ADD COLUMN IF NOT EXISTS "requested_at" timestamp with time zone;
