package cyvra.mobile.host.evidence

import cyvra.mobile.core.AndroidComponentBridge
import cyvra.mobile.core.AndroidComponentEvidencePayload
import cyvra.mobile.core.AndroidComponentExecutionResult
import cyvra.mobile.host.transport.AdbClient
import kotlinx.serialization.json.Json

/**
 * Host-side implementation of [AndroidComponentBridge] using controlled ADB transport.
 * Communicates with the optional supporting APK (`co.in.cyvra.mobile`) on the device.
 * Follows Freeze Guide §2, §5, §19, and §48:
 * - APK is an optional supporting component, NOT the sole scanner.
 * - Source is explicitly preserved as "ANDROID_COMPONENT".
 * - If APK is missing or not installed, the bridge reports `isInstalled = false` gracefully
 *   without crashing the host or halting ADB generic evidence collection.
 */
class HostAndroidComponentBridge(
    private val adbClient: AdbClient,
    private val serial: String,
    private val packageName: String = DEFAULT_PACKAGE_NAME,
    private val json: Json = Json { ignoreUnknownKeys = true },
) : AndroidComponentBridge {

    companion object {
        const val DEFAULT_PACKAGE_NAME = "co.in.cyvra.mobile"
        const val COMPONENT_RECEIVER_ACTION = "co.in.cyvra.mobile.COLLECT_EVIDENCE"
        const val COMPONENT_DATA_PATH = "/sdcard/Android/data/co.in.cyvra.mobile/files/cyvra-component-evidence.json"
    }

    override fun checkInstalled(): Boolean {
        val result = adbClient.runShell(serial, "pm list packages $packageName")
        if (!result.isSuccess) return false
        return result.stdout.lines().any { it.trim() == "package:$packageName" }
    }

    override fun getComponentVersion(): String? {
        val result = adbClient.runShell(serial, "dumpsys package $packageName")
        if (!result.isSuccess) return null
        return result.stdout.lines()
            .firstOrNull { it.trim().startsWith("versionName=") }
            ?.substringAfter("versionName=")
            ?.trim()
    }

    /**
     * Executes evidence collection on the Android Component.
     * 1. Checks installation.
     * 2. Broadcasts the trigger intent with session UUID and deviceLifecycleId.
     * 3. Pulls or reads the component-generated JSON.
     * 4. Deserializes into [AndroidComponentEvidencePayload] with source "ANDROID_COMPONENT".
     */
    override fun triggerEvidenceCollection(
        sessionUuid: String,
        deviceLifecycleId: String,
    ): AndroidComponentExecutionResult {
        if (!checkInstalled()) {
            return AndroidComponentExecutionResult(
                isInstalled = false,
                isExecutable = false,
                error = "CYVRA Android Component ($packageName) is not installed on device",
            )
        }

        val version = getComponentVersion()

        // Send broadcast or start activity with explicit extras
        val triggerCmd = "am broadcast -a $COMPONENT_RECEIVER_ACTION -n $packageName/.ComponentEvidenceReceiver " +
                "--es sessionUuid \"$sessionUuid\" --es deviceLifecycleId \"$deviceLifecycleId\""

        val triggerResult = adbClient.runShell(serial, triggerCmd)

        // Read the output JSON generated by the component
        val readResult = adbClient.runShell(serial, "cat $COMPONENT_DATA_PATH")
        if (!readResult.isSuccess || readResult.stdout.isBlank()) {
            return AndroidComponentExecutionResult(
                isInstalled = true,
                packageVersion = version,
                isExecutable = triggerResult.isSuccess,
                error = "Android Component triggered but evidence output could not be read: ${readResult.stderr.ifBlank { "File absent" }}",
            )
        }

        return try {
            val payload = json.decodeFromString<AndroidComponentEvidencePayload>(readResult.stdout.trim())
            AndroidComponentExecutionResult(
                isInstalled = true,
                packageVersion = version,
                isExecutable = true,
                payload = payload,
            )
        } catch (e: Exception) {
            AndroidComponentExecutionResult(
                isInstalled = true,
                packageVersion = version,
                isExecutable = true,
                error = "Failed to parse Android Component evidence JSON: ${e.message}",
            )
        }
    }
}
